### Get Notification Template
GET http://localhost:5151/template

### Delete Notification Template
DELETE http://localhost:5151/template/CURRENT_WEATHER_1

### Send test notification
POST http://localhost:5151/notifyemail
Content-Type: application/json

{
  "ToAddress": "jeremy.huckeba@dynabytetech.com",
  "Subject": "Test Notification",
  "TemplateId": "CURRENT_WEATHER_1",
  "Data": {
    "Date": "Saturday, April 4th",
    "TemperatureF": "75",
    "Summary": "Sunny"
  }
}