apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: demostore
auth:
  secretStore: demosecretstore
spec:
  type: state.postgresql
  version: v1
  metadata:
  - name: connectionString
    value: host=localhost user=dbuser password=LetMeInTheDB1! port=8501 connect_timeout=10 database=postgres
  - name: actorStateStore
    value: "false"